namespace EntitiesPSR
{
    public enum TablasAdministracion
    {
        TCAT_TIPOSUJETOOBJETO=7,
        CAT_PUESTOS = 9,
        CAT_NIVELESPUESTOS = 23,
        TUSUARIOS = 10,
        TUNIDADADMINISTRATIVA = 8,
        BUZON_CONFIGURACION = 24,
        TEMPLEADOS = 25,
        BUZONCONFIGURACIONFILTROS = 26,
        RROLUSUARIOENAPLICACION = 27,
        RUSUARIO_BUZON = 28,
        TGRUPOATENCION = 29,
        BUZON_CONFIGURACIONGRUPOSATENCION = 30,
        RGRUPOUSUARIO = 31,
        WORKFLOWDEFINICION = 32,
        WORKFLOWPROCESOS = 33,
        WORKFLOWPROCESOSETAPAS = 34,
        CAT_MOTIVODIASINHABILES = 35,
        CAT_DIASINHABILES = 36,
        CAT_TIPODOCUMENTOS = 15,
        CAT_TIPOSERVICIOS = 22,
        T_CASO_CONFIGURACION = 37,
        TCASOC_FORMATOS = 38,
        TCASOSC_FORMATOSECCION = 39,
        TCASO_FORMATOVARIABLE = 40,
        RCCASO_FORMATOS = 41,
        TCASOS_CONFIGURACIONTIPORESPUESTAS = 48,
        TSUJETOS = 43,
        RSUJETOCLASIFICACION = 44,
        RSUJETOSCONTACTO = 45,
        RSUJETOIDENTIFICADORES = 46,
        RSUJETODOMICILIOS = 47,
        CAT_AGRUPADORES=51,
        CAT_CLASIFICADORES=52,
        TCLASIFICACIONSUJETOS=53

    }

    public enum EntidadDeImplementacion
    {
        ENTIDAD_IMPLEMENTACION = 15
    }
    //BRAND
    public enum EntidadUsuarioCConfiguracion 
    {
        USUARIO_ACTUAL = 202
    }

    public enum CatalogoDescriptivo
    {
        BUZON = 40,
        CAT_TIPOSERVICIO = 34,
        TIPO_CASO = 6,
        TIPO_RESULTADO = 43,
        CONFIGURACION_CASO = 45,
        SECCION_DE_FORMATO = 46,
        CIRCUNSCRIPCION = 47,
        APLICA_PARA = 62,
        CLASIFICACION_CASO = 71
    }

    
}
